spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201

spring:
  profiles: dev
  application:
    name: config-dev
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
---
spring:
  profiles:
    active:
    - test
---
server: 
  port: 8202

spring:
  profiles: test
  application:
    name: config-test
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
