---
spring: 
  profiles:
    active:
    - dev
---
spring: 
  application:
    name: dept-dev
---    
spring:     
  profiles:
    active:
    - test
--- 
spring: 
  application:
    name: dept-test
---