spring: 
  profiles:
    active:
    - dev
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis的配置文件
  type-aliases-package: com.springcloud.entity #加载的实体
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mapper文件地址
  
spring:
  profiles: dev
  application:
    name: microsedept #对外暴露的服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #连接数据库的类型
    driver-class-name: com.mysql.jdbc.Driver #驱动
    url: jdbc:mysql://127.0.0.1:3306/cloud #连接地址
    username: root #账号
    password: root #密码
    dbcp2:
      min-idle: 6 #最小连接数
      initial-size: 6 #初始化连接数
      max-idle: 6 #最大连接数
      max-wait-millis: 200 #等待获取最大超时时间
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      #配置单机的 defaultZone: http://localhost:7001/eureka #注入地址，必要要和eureka server的一致
  instance:
    instance-id: microsedept8001
    prefer-ip-address: true #开启显示IP地址

info:
  app.name: deptSpringCloud #工程名称
  company.name: www.aa.com #公司名称
  build.artifactId: $project.artifactId$ #调用父工程的build
  build.version: $project.version$
---
server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis的配置文件
  type-aliases-package: com.springcloud.entity #加载的实体
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mapper文件地址
  
spring:
  profiles: test
  application:
    name: microsedept #对外暴露的服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #连接数据库的类型
    driver-class-name: com.mysql.jdbc.Driver #驱动
    url: jdbc:mysql://127.0.0.1:3306/cloud #连接地址
    username: root #账号
    password: root #密码
    dbcp2:
      min-idle: 6 #最小连接数
      initial-size: 6 #初始化连接数
      max-idle: 6 #最大连接数
      max-wait-millis: 200 #等待获取最大超时时间
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      #配置单机的 defaultZone: http://localhost:7001/eureka #注入地址，必要要和eureka server的一致
  instance:
    instance-id: microsedept8001
    prefer-ip-address: true #开启显示IP地址

info:
  app.name: deptSpringCloud #工程名称
  company.name: www.aa.com #公司名称
  build.artifactId: $project.artifactId$ #调用父工程的build
  build.version: $project.version$